### ISSUE TITLE
Wrong present from unrealized dream

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1060]
Using **Unrealized Dream** on The Dreamcatcher Device has a chance of giving you **(Postman) present** it should give you **(Explosive) present.**

**Comment by Kertie** [comment]
The item is correct since it weights 6 o.z.
[https://tibia.fandom.com/wiki/Present_(Explosive)]

What we should change is the message that shows when it is opened.

It should say: KABOOOOOOOOOOM!
![image](https://user-images.githubusercontent.com/45070560/63875729-62362780-c9c4-11e9-80ad-2c14cd0ee2a0.png)

Instead of: You open the present.
![image](https://user-images.githubusercontent.com/45070560/63875684-46cb1c80-c9c4-11e9-8524-c91ae8825faf.png)

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64025476-0fcc4680-cb3d-11e9-922c-c585ac1b0a73.png)

It's working properly.
Closed.
