### ISSUE TITLE
npc vescu (assassin addon)

### ISSUE THREAD

**Issue by TinSion** [kito2/mtibia-bounties#1080]
need make more friendly this npc , he dont take lizard scales from addon

**Comment by Kertie** [comment]
You have to write number + item

Example: If he say that he would need 20 **fish fins** in order to make the outfit.
You can answer:
fish fin / yes <-- It doesn't work.
20 fish fins / yes <-- It works.

However, it's impossible to give him 20 vampire dusts.
I tried it even using 100 vampire dusts and it doesn't work.

![image](https://user-images.githubusercontent.com/45070560/59163214-3a8a9e00-8afe-11e9-8683-98a25f4e548b.png)

**Comment by Kertie** [comment]
I updated my comment, because it was my fail.

**Comment by Kertie** [comment]
Now it's working properly.
Closed.
