### ISSUE TITLE
Can't use casks after selling house.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#169]
Date | 2018-12-26 12:53:50
-- | --
Player name | Warbeast
Position | 33639, 31960, 6
Description | Can't take out casks from depo after selling house.

**Comment by joseluis2g** [comment]
can you check this @Kertie, I think you can use house commands in test server.

**Comment by Kertie** [comment]
I would need some Tibia Coins from Kito in order to check it.

**Comment by Kertie** [comment]
1. You need a house to unwrap casks. So you can't use it after selling your house. Unless you don't buy a new house, you won't use casks anymore time.

It isn't a bug.

Closed.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/58704931-ebca5f00-83ad-11e9-971e-957ae66e509b.png)

![image](https://user-images.githubusercontent.com/45070560/58704948-fbe23e80-83ad-11e9-9198-512bbb4f4662.png)

![image](https://user-images.githubusercontent.com/45070560/58704977-19170d00-83ae-11e9-8546-4eb344ff9a39.png)

1. You can use casks on depot.
2. You can wrap it and take it out from depot.
3. The problem is that if you take it out, you won't be able to use it unless you buy a new house.
