### ISSUE TITLE
quara task

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#374]
Date | 2019-01-05 23:22:06
-- | --
Player name | Vass Yxa
Position | 32005, 32687, 7
Description | quara task

**Comment by Nahanti** [comment]
Please more information..

**Comment by kito2** [comment]
This is not a real bug, since the're two type of Quara Task:

Low level which counts Scouts Quaras, and other for high levles which just counts Quaras.

If you enable Scouts Quaras for high levels, it will unabalnce this respawn: 

![image](https://user-images.githubusercontent.com/21250744/50988195-a5519200-14ea-11e9-8bb3-ab9258e7e8f7.png)

Not a real bug, closed.
