### ISSUE TITLE
Check if imbuings works properly

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#477]
Date | 2019-01-10 14:26:44
-- | --
Player name | GM Kertie
Position | 32318, 31934, 7
Description | Siemin said: Imbuings do not work as they should, Mana Leech supposed to be 100% but he does not always return mane, he often looks mana, criticism is probably 1% instead of 10, correct it.

**Comment by kito2** [comment]
It's not a bug, it has decreasing performance on AOE damage, this means:

- If you attack a bunch of monsters with an avalanche, then instead of receiving 100% of the total damage as mana, then you will receive a diminished percent of each damage.
- If you attack a single creature with an SD or for example a paladin deals damage with his crossbow, he earns the total amount of the mana leech amount.
