### ISSUE TITLE
Player can't fight boss after necro task from Grizzly Adams.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#686]
Player **Czemu Tak** can't enter boss room after compliting necro task.
He posted cam from **24-01-2019 23:18:51** on which you can see that after reporting to Grizzly Admas he recive exp but can't enter boss room later.

**Comment by kito2** [comment]
@Nahanti I can't fix this I gues.. Or I can't think at all... There is a huge confusion related to this, since Lugri gives a tasks and grizzly adams gives a different task counts which is ok... The problems comes when the boss storage is set... But the teleports of the boss reads a unique storage and this means only one  storage will be read... can you correct somehow this boss table to properly read both storages and work?

**Comment by Kertie** [comment]
#1031 
Closed.
